name: Deploy FastAPI App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: EC2 Deployment
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip python3-venv

      - name: Deploy FastAPI App
        run: |
          cd /home/ubuntu/ &&
          rm -rf fastapi-app
          git clone https://github.com/Shumail001/Auto-Deploy.git fastapi-app
          cd fastapi-app

          # Set up Python virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt


      - name: Start FastAPI application
        run: |
          cd fastapi-app
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > uvicorn.log 2>&1 &
